# Generated by Django 2.0 on 2017-12-28 10:35

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from='name',
                unique_with=('county__name',)),
        ),
        migrations.AlterField(
            model_name='county',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False,
                                                populate_from='name',
                                                unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from='name',
                unique_with=('province__name',)),
        ),
        migrations.AlterField(
            model_name='division',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from='name',
                unique_with=('district__name',)),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from='name',
                unique_with=('division__name',)),
        ),
        migrations.AlterField(
            model_name='province',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='sublocation',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from='name',
                unique_with=('location__name',)),
        ),
    ]
