# Generated by Django 2.0 on 2017-12-28 10:35

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_facilities', '0004_auto_20151217_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255,
                                   verbose_name='Official Address'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='alternate_no_unverified',
            field=models.CharField(
                blank=True, default='', max_length=50,
                verbose_name='Official Alternate Phone Number Unverified'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='description',
            field=models.TextField(blank=True, default='',
                                   verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='fax_unverified',
            field=models.CharField(blank=True, default='', max_length=50,
                                   verbose_name='Official Fax Unverified'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='in_charge',
            field=models.CharField(blank=True, default='', max_length=255,
                                   verbose_name='In Charge'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='in_charge_title',
            field=models.CharField(blank=True, default='', max_length=255,
                                   verbose_name='Job Title of in Charge'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='landline_unverified',
            field=models.CharField(
                blank=True, default='', max_length=50,
                verbose_name='Official Land-line Unverified'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='location_description',
            field=models.TextField(blank=True, default='',
                                   verbose_name='Description of Location'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='mobile_unverified',
            field=models.CharField(blank=True, default='',
                                   max_length=50,
                                   verbose_name='Official Mobile Unverified'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='nearest_town',
            field=models.CharField(blank=True, default='', max_length=255,
                                   verbose_name='Nearest Town'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='plot_number',
            field=models.CharField(blank=True, default='', max_length=255,
                                   verbose_name='Plot Number'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='post_code',
            field=models.CharField(blank=True, default='', max_length=255,
                                   verbose_name='Post Code'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='rad_xray',
            field=models.NullBooleanField(
                default=None, help_text='Radiology Services (e.g. X-ray, MRI, '
                'Ultrascan etc)', verbose_name='RAD/XRAY'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from='name', unique=True,
                verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='town',
            field=models.CharField(blank=True, default='', max_length=255,
                                   verbose_name='Town'),
        ),
    ]
